example : Thread.o main.o Scheduler.o 
	gcc -o example Thread.o main.o
Thread.o : Thread.c
	gcc -c -o Thread.o Thread.c
main.o : main.c
	gcc -c -o main.o main.c
Scheduler.o : Scheduler.c
	gcc -c -o Scheduler.o Scheduler.c
